[book]
title = "D2X Book Template | 动手学书籍模板"
author = "Author Name"
language = "en"

[build]
build-dir = "book"

[output.html]
git-repository-url = "https://github.com/Sunrisepeak/xlings"

[preprocessor.foo]
# Add any additional configurations
